### ISSUE TITLE
The code for metrics

### ISSUE THREAD

**Issue by QiaoSiBo** [HongrongWei/CLAS-Pytorch#1]
Would you provide the code for calculating the Volumes (EDV & ESV) and ejection fraction (EF) and others metrics? Thanks!

**Comment by HongrongWei** [comment]
Hi, we calculate the clinical metrics (EDV, ESV, EF) based on the evaluation platform of CAMUS challenge (website: http://camus.creatis.insa-lyon.fr/challenge/#phase/5ca211272691fe0a9dac46d6) to ensure the fairness of the evaluation. As for the segmentation metrics on the training set, we use medpy (https://pypi.org/project/MedPy/).

**Comment by QiaoSiBo** [comment]
Thanks！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HongrongWei/CLAS-Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月17日(星期四) 下午2:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HongrongWei/CLAS-Pytorch] The code for metrics (#1)





 
Hi, we calculate the clinical metrics (EDV, ESV, EF) based on the evaluation platform of CAMUS challenge (website: http://camus.creatis.insa-lyon.fr/challenge/#phase/5ca211272691fe0a9dac46d6) to ensure the fairness of the evaluation. As for the segmentation metrics on the training set, we use medpy (https://pypi.org/project/MedPy/).
